### ISSUE TITLE
Add support for configuring IPFIX export to operator GUI

### ISSUE THREAD

**Issue by rupertgregoryibm** [netobserv/network-observability-operator#296]
Recently support for IPFIX export has been added to the agent and FLP however these configuration options are not yet exposed in the netobserv operator configuration GUI.

We should enhance the exporters section of the operator to support IPFIX as an option (as well as update the schema defs etc to support these new parameters)

This will allow users to simply type in a flow receiver IP address & port and start to receive flow; enabling insight in to OS based environments using existing tooling they may have in place such as IBM SevOne NPM (https://www.ibm.com/products/sevone-network-performance-management)

(Bonus points for exposing other settings to the GUI such as sampling rate)

![image](https://user-images.githubusercontent.com/127860475/225018569-34e84d15-9f22-4b94-bcf2-80c8c1f4ae38.png)

**Comment by jotak** [comment]
FYI @acmenezes is currently on it

**Comment by rupertgregoryibm** [comment]
Thank you both!. Let me know if you need any input or testing.

**Comment by jotak** [comment]
Hey @rupertgregoryibm 
Here's the current pull request, in case you want to review before merge: https://github.com/netobserv/network-observability-operator/pull/311

Example of CRD config that it would provide:

```yaml
# ...
  exporters:
    - type: IPFIX
      ipfix:
        targetHost: "ipfix-collector.ipfix.svc.cluster.local"
        targetPort: 4739
        transport: tcp
        enterpriseId: 42
```
